### PR TITLE
Created a GitHub actions workflow

### PR DESCRIPTION
**Pull request by 2010person**
Hi @rocketman12435 , 
I have created a GitHub actions bot which will give a personalised comment to anyone who submits a pull request to this repo, if you merge it.  See https://github.com/2010person/yourlostitems.github.io/pull/2 for an example.

### CODE REVIEW

**Comment by werdl** [comment]
Cool!

**Review by thisiscoding1234 — COMMENTED** [review]
For the GITHUB_TOKEN and the url, what do they need?

**Comment by 2010person** [comment]
GITHUB token - https://docs.github.com/en/actions/security-guides/automatic-token-authentication
Pr url is the url of the pull request which it gets

**Comment by thisiscoding1234** [comment]
What are the permissions needed for the TOKEN?

**Comment by thisiscoding1234** [comment]
Ok will look at this

**Comment by 2010person** [comment]
It should work if somebody submits another pupil request to this repo.

**Pull request merged**
