### PR TITLE
Added flask + dependabot + requirements.txt  +  codeql + fixed typos in custom workflow

### PR DESCRIPTION
**Pull request by 2010person**
The file structure had to be changed as @rocketman12435 wants to add Flask.

### CODE REVIEW

**Comment by 2010person** [comment]
Also fixed some typos in the custom github actions workflow, to make it work. Sorry

**Comment by 2010person** [comment]
Also you can't run this on GitHub Pages, so you will have to find somewhere else like Replit.

**Comment by thisiscoding1234** [comment]
This should really be in a separate repo. I can add you to it if you like?

**Comment by 2010person** [comment]
Idk @rocketman12435 wanted this, ask him?

**Comment by 2010person** [comment]
@rocketman12435 are you going to merge this?

**Comment by rocketman12435** [comment]
No

**Comment by rocketman12435** [comment]
Can't do this

**Comment by uimaxbai1** [comment]
a

**Comment by uimaxbai1** [comment]
a

**Pull request closed without merging**
