### PR TITLE
Make more modular

### PR DESCRIPTION
**Pull request by thisiscoding1234**
Making the site more modular

### CODE REVIEW

**Comment by thisiscoding1234** [comment]
# And also compacted the code

**Comment by thisiscoding1234** [comment]
Can @uimaxbai and @werdl also review, please?

**Comment by rocketman12435** [comment]
We don’t need them right now maybe later

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thisiscoding1234** [comment]
They are on the project, so they can do things to do with it. They are needed.

**Comment by werdl** [comment]
Happy to help if needed!

**Comment by thisiscoding1234** [comment]
Also "Sent from my iPhone" is sooo tacky.

**Comment by thisiscoding1234** [comment]
Please re-add them!

**Comment by Yeetface513** [comment]
skibidi

**Comment by werdl** [comment]
Why have I been removed from the organisation @rocketman12435? I understand if you no longer need me to contribute though, so could you please clarify?

**Comment by thisiscoding1234** [comment]
> Happy to help if needed!

Please do a review of my code

**Review by Yeetface513 — APPROVED** [review]
looks good as far as I can see, very solid changes

**Comment by thisiscoding1234** [comment]
> looks good as far as I can see, very solid changes

image

**Comment by Neodx2** [comment]
it means gay

**Pull request merged**
